### ISSUE TITLE
Any Plans for the vienna.rb github org and the broken (dead) ruby vienna meetup website in 2023?

### ISSUE THREAD

**Issue by geraldb** [vienna-rb/vienna-rb.github.com#103]
Hello,

cc:  @hola-soy-milk,  @aaroncm 

   as some of you might remember I tried for years (with many in person show-ups and the work ready-to-merge) to update the meetup website.

 If I dare to say it is kind of ridiculous and obviously it reflects on the state-of-the-meetup.  Bascially it says that it's game over and nobody is here.   Please, correct me if I am wrong, thank you.   Happy new year. Cheers. Prosit 2023!

PS:  To "save" the work about the updates as you might know I started a new github org with a working ruby meetup website, see <https://github.com/viennarb>.

PPS:  One plan / idea is to "merge" e.g.  transfer all repos to the new org, for example, and I am happy to preserve the legacy / heritage (and put in the couple of hours required.)

**Comment by mraaroncruz** [comment]
Let's see how reviving the meetup goes. If people are still interested, we'll consider reviving the website.
Merging is not something we're looking into.

Closing for now.

PS. You @'d someone who I don't believe has ever been in the Vienna Ruby Community
