### ISSUE TITLE
Vienna.rb Static Site V2.0  (Using "Plain Vanilla" Jekyll w/ GitHub Pages) - No More Octopress, Built Step, Multiple Branches etc.

### ISSUE THREAD

**Issue by geraldb** [vienna-rb/vienna-rb.github.com#49]
Hello,
  @FloorD @alicetragedy @pferdefleisch 
  If you're interested I've started to convert the vienna.rb static site to use the latest and greatest technology, that is, "plain vanilla" Jekyll with auto-built (integration) with GitHub pages. Still a little early and missing some polish you can find the [source here](https://github.com/geraldb/viennarb) and a [live example here](http://geraldb.github.io/viennarb) (auto-built w/ GitHub pages)    PS: If there's any interest in updating the website  I volunteer, for example, for next month (e.g. November) to a talk, for example, "Inisde the (new) Vienna.rb static (web) site (and how you can contribute). If there's any interest we can add job listings, a member directory, etc.

**Comment by FloorD** [comment]
Hey @geraldb @alicetragedy @pferdefleisch 
After ranting extensively about meetup.com and our dinosaur website on 'the twitters' multiple people actually suggested using onruby.de, killing two flies with one stone. The list of Ruby meetups already using it is quite impressive: http://www.onruby.de/

Is this something we could all be happy with?

**Comment by alicetragedy** [comment]
@FloorD I'm 100% for using onruby.de, already told Peter we'd be happy to have his help on this if needed. :+1: 
However I think our site is in need of a fix anyway and this has little to do with meetup, unless we move the picks and such to the alternative listing. What do you think? is it too much work? Afaik it has a lot of cool features for meetup groups but nothing similar to a blog functionality. If we keep doing the picks, I'd like to at least fix the couple of bug-ish things in our blog. :sparkles:

**Comment by geraldb** [comment]
Disclaimer - I'm just a regular member - I'm fine with whatever you decide or what works best for you - as always thanks for your efforts for keeping the group going.

My two cents  - I'm always supportive of trying out new things and a fan of hands-on experience. If anyone can manage to set up onruby for vienna and keep it going, that be fantastic. Definitely more personality than a "plain old" meetup.com page. Big plus - great to see the cross-promotion of Ruby groups. 

Best of of both worlds? Not sure how the blog fits into the onruby setup - as far as I can tell it's more of a meetup killer with many goodies e.g. forum (?), jobs (?), etc.   Not sure how it handles a blog -  if interested I'm happy to upgrade (migrate) the picks/blog to a simple "plain vanilla" static site that can get, for example. linked from the new vienna.onruby site and vice versa. Cheers.

**Comment by geraldb** [comment]
I tried  :-), see  <https://github.com/vienna-rb/new-blog>.  All the best.
